### ISSUE TITLE
Show a message in the list view when no videos found

### ISSUE THREAD

**Issue by kjartanvest** [SYNQfm/SYNQ-Android#16]
"You have not uploaded any videos yet", or "No videos available for playback)

**Comment by jettlin** [comment]
In progress...

**Comment by jettlin** [comment]
Branch:  issue_16
Status:  pending pull request
Comments:  Added a couple of things -

- Icons rather than text
- Title bar shows on the uploaded video list page
- Progressbar (indeterminate, couldn't get it to change to determinate) over videos while uploading
- Message showing that there are no available video(s)
- Changed icon to the SYNQ Icon instead of the Android icon

@gsemino -> Just making sure you see this

**Comment by jettlin** [comment]
This should have been merged already.  Will be redone as part of the screen reorg
